version: "3"
services:
  asterion.loc:
    build: .
    environment:
      PHP_IDE_CONFIG: "serverName=asterion.loc"
    volumes:
      - ./www:/var/www:delegated
    entrypoint:
      - sh
      - -c
      - set -x && docker-php-ext-enable xdebug && touch /tmp/xdebug.log && chmod 0777 /tmp/xdebug.log && /bin/bash /docker.sh
    labels:
      - "traefik.backend=asterion.loc"
      - "traefik.frontend.rule=HostRegexp: asterion.loc,{subdomain:(.+[.])+}asterion.loc"
      - "traefik.docker.network=docker-www"
      - "traefik.port=80"
    networks:
      - default
      - proxy

networks:
  proxy:
    external:
      name: docker-www
