version: "3"
services:
  asterionrpg:
    environment:
      PROJECT_ENVIRONMENT: "prod"
    volumes:
      - ./etc/home:/etc/home:delegated
    ports:
      - "80:80"
      - "443:443"
    restart: "always"
