version: "3"
services:
  asterionrpg.cz:
    build: .
    environment:
      PROJECT_ENVIRONMENT: "prod"
      XDEBUG_CONFIG: "remote_host=172.17.0.1 remote_enable=1 idekey=PHPSTORM remote_log=/tmp/xdebug.log"
    volumes:
      - ./www:/var/www:delegated
    labels:
      - "traefik.backend=asterionrpg.cz"
      - "traefik.frontend.rule=HostRegexp: asterionrpg[.]cz,{subdomain:(.+[.])+}asterionrpg[.]cz"
      - "traefik.docker.network=docker-www"
      - "traefik.port=80"
    networks:
      - default
      - proxy

networks:
  proxy:
    external:
      name: docker-www
