version: "3"
services:
  drdplus.loc:
    build: .
    environment:
      PHP_IDE_CONFIG: "serverName=drdplus.loc"
    volumes:
      - ./www:/var/www:delegated
    command: /bin/bash -c 'cd /var/www/update.blog && sudo -u www-data npm install && sudo -u www-data /docker.sh'
    labels:
      - "traefik.backend=drdplus.loc"
      - "traefik.frontend.rule=HostRegexp: {subdomain:([[:alnum:]]+[.])+}drdplus.loc"
      - "traefik.docker.network=docker-www"
      - "traefik.port=2015"
    networks:
      - default
      - proxy

networks:
  proxy:
    external:
      name: docker-www
