version: "3"
services:
  asterionrpg:
    build: .
    environment:
      PROJECT_ENVIRONMENT: "prod"
    volumes:
      - ./www:/var/www:delegated
    labels:
      - "traefik.backend=asterionrpg"
      - "traefik.frontend.rule=HostRegexp: asterionrpg.cz,{subdomain:(.+[.])+}asterionrpg.cz"
      - "traefik.docker.network=docker-www"
      - "traefik.port=80"
    networks:
      - default
      - proxy
    restart: always

networks:
  proxy:
    external:
      name: docker-www
